name: Test

on:

  pull_request:
    types: [ opened, synchronize ]

  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: go test
